language: csharp
solution: ./Net35Essentials.sln
sudo: required

install:
  - sudo apt-get install nunit-console
  - nuget restore ./Net35Essentials.sln

before_script:
  - chmod +x ./lib/BuildDependencies.sh
  - chmod +x ./tests/RunTests.sh

script:
  - cd "$TRAVIS_BUILD_DIR/lib"
  - ./BuildDependencies.sh
  - cd "$TRAVIS_BUILD_DIR"
  - xbuild ./Net35Essentials.sln
  - cd "$TRAVIS_BUILD_DIR/tests"
  - ./RunTests.sh
  - cd "$TRAVIS_BUILD_DIR"